INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (8, 'RISK', 'Heute geht es mir echt beschissen', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (9, 'RISK', 'Heute war ein scheiß Tag', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (10, 'RISK', 'Ich möchte einfach nicht mehr', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (11, 'RISK', 'Ich will nicht mehr', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (12, 'RISK', 'Keinen Bock mehr', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (13, 'RISK', 'Was soll ich nur tun?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (14, 'RISK', 'Mein Leben ist scheiße', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (15, 'RISK', 'Ich möchte nicht mehr Leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (16, 'RISK', 'Ich sehe keinen Sinn mehr im Leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (17, 'RISK', 'Ich sehe einfach keinen Sinn mehr', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (18, 'RISK', 'Scheiß Tag', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (19, 'RISK', 'Ich weiß einfach nicht mehr weiter', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (20, 'RISK', 'Ich komme einfach nicht weiter', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (21, 'RISK', 'Ich kann nicht mehr', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (22, 'RISK', 'Sehe keinen Sinn mehr im Leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (23, 'RISK', 'Kein Bock mehr auf das scheiß Leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (24, 'RISK', 'Was soll ich jetzt tun? Ich weiß nicht mehr weiter', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (25, 'RISK', 'Was bleibt mir jetzt im Leben noch?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (26, 'RISK', 'Was kann ich in meiner Situatino noch tun?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (27, 'RISK', 'Alle behandeln mich ungerecht', 'Das ist bestimmt nur subjektiv, die Realität sieht anders aus');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (28, 'ADVICE', 'Was kann ich gegen Kopfschmerzen machen?', 'Viel trinken');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (29, 'RISK', 'Hilfe, ich fühle mich ungerecht behandelt', 'Oh nein was ist passiert?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (30, 'RISK', 'Hilfe, ich fühle mich ungerecht behandelt', 'Warum ?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (31, 'RISK', 'Hilfe, ich fühle mich ungerecht behandelt', 'Was ist passiert?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (32, 'RISK', 'Hilfe, ich fühle mich ungerecht behandelt', 'Wer hat dich ungerecht behandelt?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (33, 'RISK', 'Hilfe, ich fühle mich ungerecht behandelt', 'Wie wurdest du behandelt?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (34, 'GREETING', 'Hi', 'Hi');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (35, 'GREETING', 'Servus wie gehts?', 'Hey mir gehts gut und dir?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (36, 'GREETING', 'Hallo', 'Hey');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (38, 'GREETING', 'Hallo', 'Hallo');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (39, 'GREETING', 'Hallo', 'Hey');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (40, 'GREETING', 'Hi', 'Hey');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (41, 'GREETING', 'Na alles klar?', 'Ja alles gut und selbst?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (42, 'GREETING', 'Na alles klar?', 'Ja und bei dir?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (43, 'GREETING', 'Na alles klar?', 'Ja mir geht es gut und dir?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (44, 'GREETING', 'Servus', 'Hey, alles klar bei dir?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (45, 'GREETING', 'Hallöchen', 'Hey');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (46, 'GREETING', 'Heyho', 'Hey');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (47, 'GREETING', '', 'Hallo, kann ich dir helfen?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (48, 'GREETING', '', 'Hallo, wie kann ich dir weiterhelfen?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (49, 'RISK', 'Es ist doch alles beschissen', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (50, 'RISK', 'Mein Leben macht keinen Sinn mehr', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (51, 'RISK', 'Mein Leben macht keinen Sinn mehr', 'Warum denkst du so etwas schlimmes?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (52, 'RISK', 'Mein Leben macht keinen Sinn mehr', 'Warum sollte dein Leben keinen Sinn mehr machen?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (53, 'RISK', 'Ich will sterben', 'Was? Auf keinen Fall');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (54, 'RISK', 'Ich will nur noch sterben', 'Was? Auf keinen Fall');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (55, 'RISK', 'Ich will einfach nur noch sterben', 'Was? Auf keinen Fall');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (56, 'RISK', 'Ich möchte meinem Leben ein Ende setzen', 'Was? Auf keinen Fall');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (57, 'RISK', 'Ich möchte mein Leben beenden', 'Was? Auf keinen Fall');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (58, 'RISK', 'Ich möchte nicht mehr Leben', 'Was? Auf keinen Fall');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (59, 'RISK', 'Ich will mich umbringen', 'Was? Auf keinen Fall');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (60, 'RISK', 'Finde mein Leben sinnlos', 'Was? Auf keinen Fall');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (61, 'RISK', 'Warum ist mein Leben so scheiße?', 'Ich glaube nicht, dass es so ist');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (62, 'RISK', 'Wie finde ich wieder Kraft?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (63, 'RISK', 'Ist so etwas überhaupt noch normal?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (64, 'RISK', 'Was stimmt nicht mit mir?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (65, 'RISK', 'Ich halte keinen Job mehr psychisch durch, was soll ich bloß tun?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (66, 'RISK', 'Ich weiß nicht mehr weiter - was mache ich falsch?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (67, 'RISK', 'Warum bin ich nicht normal?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (68, 'RISK', 'Ich habe mich selbst verloren, wer kennt den Weg?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (69, 'RISK', 'Was ist an mir so falsch?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (70, 'RISK', 'Wie soll ich mein Leben je wieder in den Griff bekommen?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (71, 'RISK', 'Hat das Leben noch einen Sinn?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (72, 'RISK', 'Ich bin verzeifelt', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (73, 'RISK', 'Macht es noch Sinn weiter zu machen?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (74, 'RISK', 'Warum ist mein Leben grau und beschissen?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (75, 'RISK', 'Wie sehe ich Dinge wieder positiv?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (76, 'RISK', 'Was stimmt mit mir nicht?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (77, 'RISK', 'Ich kann nicht mehr. Was ist nur mit mir los?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (78, 'RISK', 'Was kann ich tun, wenn wieder alles sinnlos erscheint?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (79, 'RISK', 'Wie soll ich mich beruhigen?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (80, 'RISK', 'Was zur Hölle ist mit mir los?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (81, 'RISK', 'Was stimmt nicht mit meinem Leben?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (82, 'RISK', 'Wieso kann ich nicht glücklich sein?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (83, 'RISK', 'Was ist los mit mir?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (84, 'RISK', 'Was ist mit mir los?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (85, 'RISK', 'Was ist bloß falsch bei mir?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (86, 'RISK', 'Will nicht mehr weiterleben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (87, 'RISK', 'Hat das alles noch Sinn?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (88, 'RISK', 'Was hilft gegen meine Leere?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (89, 'RISK', 'Wie soll ich jetzt nur weitermachen?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (90, 'RISK', 'Warum mache ich alles falsch?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (91, 'RISK', 'Ich kann so nicht weiter leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (92, 'RISK', 'Ich will so nicht weiter leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (93, 'RISK', 'Ich kann nicht mehr weiter leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (94, 'RISK', 'Ich will nicht mehr weiter leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (95, 'RISK', 'Mein Leben ist nicht mehr lebenswert', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (96, 'RISK', 'Ich bin am Ende', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (97, 'RISK', 'Ich bin frustiert und unglücklich', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (98, 'RISK', 'Hat mein Leben noch einen Sinn?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (99, 'RISK', 'Hat mein Leben überhaupt noch einen Sinn?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (100, 'RISK', 'Ich brauche Hilfe', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (101, 'RISK', 'Ich will mich umbringen', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (102, 'RISK', 'Warum wird Suizid eigentlich angekündigt', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (103, 'RISK', 'Ich will suizid begehen', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (104, 'RISK', 'Ich denke an Suizid', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (105, 'RISK', 'Ich glaube es macht keinen Sinn mehr weiter zu leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (106, 'RISK', 'Ich denke es macht keinen Sinn mehr weiter zu leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (107, 'RISK', 'Ich finde es macht keinen Sinn mehr weiter zu leben', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (108, 'SMALL_TALK', 'Mir geht es gut und wie geht es dir?', 'Mir auch, was hast du heute gemacht?');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (109, 'SMALL_TALK', 'Ich war heute joggen', 'Cool! Du bist bestimmt sportlich');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (110, 'SMALL_TALK', 'Anscheinend soll morgen schönes Wetter werden', 'Cool! Da freue ich mich schon drauf');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (111, 'SMALL_TALK', 'Anscheinend soll morgen schlechtes Wetter werden', 'Mist!');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (112, 'SMALL_TALK', 'Morgen soll es regnen', 'Echt? Mist, ich wollte laufen gehen');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (113, 'SMALL_TALK', 'Was hast du heute vor?', 'Echt? Mist, ich wollte laufen gehen');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (114, 'SMALL_TALK', 'Was willst du machen?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (115, 'SMALL_TALK', 'Wie hat dir Matrix gefallen?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (116, 'SMALL_TALK', 'Und wie war dein Urlaub?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (117, 'SMALL_TALK', 'Wo warst du in den Ferien?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (118, 'SMALL_TALK', 'War das Wetter gut?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (119, 'SMALL_TALK', 'Lass uns doch mal zusammen joggen gehen', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (120, 'SMALL_TALK', 'Hast du Lust Tennis spielen zu gehen?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (121, 'SMALL_TALK', 'Ich war im Urlaub und du?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (122, 'SMALL_TALK', 'Ich war in 2 Wochen in Schweden, warst du auch im Urlaub?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (123, 'SMALL_TALK', 'Was hast du in deiner freien Zeit gemacht?', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (124, 'SMALL_TALK', 'Ich glaube bei schönem Wetter werden Fußball spielen gehen', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (125, 'SMALL_TALK', 'Bei schönem Wetter spiele ich meistens Fußball', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (126, 'SMALL_TALK', 'Bei schönem Wetter spiele ich meistens Tennis', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (127, 'SMALL_TALK', 'Bei schönem Wetter spiele ich meistens Volleyball', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (128, 'SMALL_TALK', 'Wenn es nicht regnet dann spiele ich Tennis', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (129, 'SMALL_TALK', 'Wenn es nicht regnet dann spiele ich Fußball', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (130, 'SMALL_TALK', 'Wenn es nicht regnet dann spiele ich Tischtennis', '');
INSERT INTO public.t_qa_pair (id, intent, question, answer) VALUES (131, 'SMALL_TALK', 'Wenn es nicht regnet dann spiele ich Volleyball', '');