micronaut:
  server:
    port: 18080
    name: qa-backend
    cors:
      enabled: true
  http:
    client:
      read-timeout: -1
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: veryhardsecretthatnoonewilleverknow

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/qa
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 250
    username: qa
    password: qa



flyway:
  datasources:
    default:
      locations: classpath:db.migration
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
headers:
  classification:
    - text
    - label
  answer_selection:
    - text
    - response
    - task
seq2seq:
  prefix: seq2seq
dst:
  prefix: dst



